djangonautic/accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name ='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('user/<username>', views.update_profile, name="profile"),
]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="article_list"),
    path('create', views.article_create, name="create"),
    path('<slug>', views.article_detail, name="detail"),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/', views.about, name="About"),
    path('', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User
from articles.choices import *

class Article(models.Model):
    title = models.CharField(max_length=100)
    feel = models.IntegerField(choices=FEEL_CHOICE, default=1)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete= models.CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

djangonautic/accounts/forms.py
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('url', 'location', 'company')

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'feel', 'body', 'slug', 'thumb',]

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout
from django.db import transaction

def signup_view(request):
    if request.method=='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return  redirect('articles:article_list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.htm', {'form': form})

def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:article_list')
            return redirect('articles:article_list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.htm', {'form': form})

def logout_view(request):
    if request.method =='POST':
        logout(request)
        return redirect('articles:article_list')

@login_required
@transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Your profile was successfully updated!'))
            return redirect('settings:profile')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profiles/profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

djangonautic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    article = Article.objects.all().order_by('-date')
    return render(request, 'articles/article_list.htm', {'articles': article})

def article_detail(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.htm', {'article': article})

@login_required(login_url="/accounts/login")
def article_create(request):
    if request.method =='POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:article_list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.htm', {'form': form})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse("homepage")
    return render(request, 'homepage.htm')

def about(request):
    #return HttpResponse("about")
    return render(request, 'about.htm')

djangonautic/accounts/templates/accounts/login.htm
{% extends 'base_layout.htm' %}

{% block content %}
  <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">{% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" name="" value="Login">
  </form>
{% endblock%}

djangonautic/accounts/templates/accounts/signup.htm
{% extends 'base_layout.htm' %}

{% block content %}
  <h1>Signup</h1>
  <form class="site-form" action="{% url 'accounts:signup' %}" method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" name="" value="Signup">
  </form>
{% endblock%}

djangonautic/accounts/templates/accounts/user_profile.htm
{% extends 'base_layout.htm' %}

{% block content %}
  <h2>{{ user.get_full_name }}</h2>
  <ul>
    <li>Username: {{ user.username }}</li>
  </ul>
{% endblock %}

djangonautic/articles/templates/articles/article_create.htm
{% extends 'base_layout.htm' %}
{% block content %}
<div class="create-article">
    <h2>Create an Awesome New Article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="Create">
    </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock%}

djangonautic/articles/templates/articles/article_detail.htm
{% extends 'base_layout.htm' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumb.url }}">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{% endblock%}

djangonautic/articles/templates/articles/article_list.htm
{% extends 'base_layout.htm' %}

{% block content %}
    <h1>List of Articles</h1>
    <div class="articles">
    {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
        <p class="feel">{{ article.get_feel_display }}</p>
        <p>{{ article.snippet }}</p>
        <p>{{ article.date }}</p>
        <p class="author">{{ article.author.username }}</p>
      </div>
    {% endfor %}
    </div>
{% endblock%}

djangonautic/templates/about.htm
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>We like Django</p>
  </body>
</html>

djangonautic/templates/base_layout.htm
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  </head>
  <body>
    <div class="wrapper">
      <header>
        <a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a>
          <nav>
            <ul>
              {% if user.is_authenticated %}
            <li>
              <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Logout</button>
              </form>
            </li>
            <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a> </li>
            {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a> </li>
            <li><a href="{% url 'accounts:signup' %}">Signup</a> </li>
            {% endif %}
          </ul>
          </nav>
      </header>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

djangonautic/templates/homepage.htm
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HomePage</title>
  </head>
  <body>
    <h1>This is the HomePage</h1>
    <p>Welcome tooooooooooooooooo DjangoNautic</p>
  </body>
</html>

templates/homepage.htm
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>HomePage</title>
  </head>
  <body>
    <h1>This is the HomePage</h1>
    <p>Welcome tooooooooooooooooo DjangoNautic</p>
  </body>
</html>